### ISSUE TITLE
Practitioner pouch doesn't work with "Ritual of Ancient Stone"

### ISSUE THREAD

**Issue by groting** [Mithion/Mana-And-Artifice#1013]
**Describe the bug**

When you use practitioner pouch with "Ritual of Ancient Stone" selected on empty space nothing happens. If you use it on metalic runes, all reagents will be used but ritual doesn't start.

**To Reproduce**

1. Select "Ritual of Ancient Stone" in practitioner pouch
2. Have all nedeed reagents 
3. Use it on big flat surface
4. or Use it on metalic runes 

**Expected behavior**

Ritual will start.

Version Information (please complete the following information):

Mod Version: 3.1.0.1
Forge Version 47.3.11

Additional context:

geckolib-forge-1.20.1-4.4.9
curios-forge-5.10.0+1.20.1

When it happens on server, server send message: 

 [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@29093412, suppressing error
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 7
at com.mna.recipes.rituals.RitualRecipe.lambda$getMatchedDirection$10(RitualRecipe.java:715) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23339!/:3.1.0.1] {re:classloading}
at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
at com.mna.recipes.rituals.RitualRecipe.getMatchedDirection(RitualRecipe.java:714) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23339!/:3.1.0.1] {re:classloading}
at com.mna.items.ritual.ItemPractitionersPouch.getStoredRitualRotation(ItemPractitionersPouch.java:424) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23339!/:3.1.0.1] {re:classloading}
at com.mna.items.ritual.ItemPractitionersPouch.placeRitual(ItemPractitionersPouch.java:210) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23339!/:3.1.0.1] {re:classloading}
at com.mna.items.ritual.ItemPractitionersPouch.m_6225_(ItemPractitionersPouch.java:1090) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23339!/:3.1.0.1] {re:classloading}

**Comment by groting** [comment]
Add info: Seems to happen only when ritual placed in certain direction.

**Comment by ShelLuser** [comment]
> Add info: Seems to happen only when ritual placed in certain direction.

What direction?  My friend Aya (survival) and me (creative) tried to reproduce but we don't experience the same issues. However..  we're on Forge 47.3.0.

**Comment by groting** [comment]
North. East works as intended.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
