### ISSUE TITLE
Rituals not working

### ISSUE THREAD

**Issue by Serifina** [Mithion/Mana-And-Artifice#187]
No ritual seems to be able to be activated. I've tested most rituals, and had no effect. Sound effect plays, but nothing actually happens. Checking the log, and this error applies every time:

`[14Mar2021 19:54:50.387] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.entity.EntityType.handler$zfp000$spawnFromItemStack(EntityType.java:636) ~[?:?]
	at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:313) ~[?:?]
	at com.ma.items.ritual.ItemPurifiedVinteumDust.spawnRitualEntity(ItemPurifiedVinteumDust.java:143) ~[mana-and-artifice:1.3.0.5]
	at com.ma.items.ritual.ItemPurifiedVinteumDust.func_195939_a(ItemPurifiedVinteumDust.java:85) ~[mana-and-artifice:1.3.0.5]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:643) ~[forge:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:187) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:353) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[14Mar2021 19:54:55.554] [Server thread/ERROR] [com.ma.ManaAndArtifice/]: Failed to parse UUID for ritual caster.  Giving up and completing the ritual anyway, but some effects may not apply!
[14Mar2021 19:55:02.754] [Server thread/ERROR] [com.ma.ManaAndArtifice/]: Failed to parse UUID for ritual caster.  Giving up and completing the ritual anyway, but some effects may not apply!`

Attached is the whole log file. The modpack this is in is a new one (made by me), located here: https://www.curseforge.com/minecraft/modpacks/the-phoenixs-assorted-goodies-a-generalist

[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/6138512/latest.log)

**Comment by Serifina** [comment]
Thanks to the efforts of one of my players, the culprit was found: The "cracking spawn eggs" feature of the mod Forgery.
