### ISSUE TITLE
Ticking entity caused when server restarts during ritual

### ISSUE THREAD

**Issue by Xenovalis** [Mithion/Mana-And-Artifice#195]
If a server restarts when a ritual is in the middle of activation it causes a ticking entity. Ran into this when the server's autorestart script kicked in when I was doing a ritual of visiting.

```
Time: 3/20/21 12:02 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
        at com.ma.rituals.effects.RitualEffectVisit.applyRitualEffect(RitualEffectVisit.java:37) ~[mana-and-artifice:1.3.0.2] {re:classloading}
        at com.ma.api.rituals.RitualEffect.onRitualCompleted(RitualEffect.java:52) ~[mana-and-artifice:1.3.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at com.ma.entities.rituals.EntityRitual.logic_processRitual(EntityRitual.java:260) ~[mana-and-artifice:1.3.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at com.ma.entities.rituals.EntityRitual.runStateLogic(EntityRitual.java:143) ~[mana-and-artifice:1.3.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at com.ma.entities.rituals.EntityRitual.func_70071_h_(EntityRitual.java:349) ~[mana-and-artifice:1.3.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
```

```
-- Entity being ticked --
Details:
        Entity Type: mana-and-artifice:ritual_entity (com.ma.entities.rituals.EntityRitual)
        Entity ID: 345
        Entity Name: entity.mana-and-artifice.ritual_entity
        Entity's Exact location: 49.50, 90.00, -120.50
        Entity's Block location: World: (49,90,-121), Chunk: (at 1,5,7 in 3,-8; contains blocks 48,0,-128 to 63,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
        Entity's Momentum: 0.00, 0.00, 0.00
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the 1.4.0.0 release.
