### ISSUE TITLE
Random Cilent Crash

### ISSUE THREAD

**Issue by Kurojime** [Mithion/Mana-And-Artifice#284]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/11/21 2:18 PM
Description: Ticking entity

java.lang.ClassCastException: com.ma.entities.faction.WitchHunterArrow cannot be cast to net.minecraft.entity.LivingEntity
	at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:193) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1040_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2546/741125012.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:locks.mixins.json:ForgeHooksAccessor,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:META-INF/sneakymagic.mixins.json:accessor.IAbstractArrowEntityAccessor,pl:mixin:A}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:META-INF/sneakymagic.mixins.json:accessor.IAbstractArrowEntityAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:locks.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$15974/1172787205.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:locks.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:locks.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$15132/1452478091.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:193) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1040_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2546/741125012.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:locks.mixins.json:ForgeHooksAccessor,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:META-INF/sneakymagic.mixins.json:accessor.IAbstractArrowEntityAccessor,pl:mixin:A}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:META-INF/sneakymagic.mixins.json:accessor.IAbstractArrowEntityAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:locks.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$15974/1172787205.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: mana-and-artifice:witch_hunter_arrow (com.ma.entities.faction.WitchHunterArrow)
	Entity ID: 8579
	Entity Name: Witch Hunter
	Entity's Exact location: -18.61, 31.95, 454.57
	Entity's Block location: World: (-19,31,454), Chunk: (at 13,1,6 in -2,28; contains blocks -32,0,448 to -17,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -1.47, -0.10, 0.55
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:locks.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:locks.mixins.json:ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['FazeAlpha'/6172, l='ServerLevel[The Elder Scrolls]', x=-46.36, y=76.77, z=496.59]]
	Chunk stats: ServerChunkCache: 2526
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,67,208), Chunk: (at 0,4,0 in -8,13; contains blocks -128,0,208 to -113,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7395 game time, 7395 day time
	Level name: The Elder Scrolls
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 76733 (now: false), thunder time: 110084 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:marg.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$15132/1452478091.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2347594312 bytes (2238 MB) / 4496293888 bytes (4288 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.17.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.17.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.17.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.17.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.17.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.17
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.16.5-1.11.4.jar                     |Cyclops Core                  |cyclopscore                   |1.11.4              |DONE      |NOSIGNATURE
		Hermaeus+Mora+v1+-+1.16.5.jar                     |Hermaeus Mora Mod             |hermaeusmoramod               |1.0                 |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |NOSIGNATURE
		locks-1.16.5-3.0.3.jar                            |Locks                         |locks                         |3.0.3               |DONE      |NOSIGNATURE
		ColdSteel(FORGE_1.16.5)vrs1.0.9.jar               |Cold Steel                    |coldsteel                     |1.16.4-1.0.9        |DONE      |NOSIGNATURE
		jei-1.16.5-7.6.4.90.jar                           |Just Enough Items             |jei                           |7.6.4.90            |DONE      |NOSIGNATURE
		EverlastingAbilities-1.16.5-1.7.1.jar             |EverlastingAbilities          |everlastingabilities          |1.7.1               |DONE      |NOSIGNATURE
		AttributeFix-1.16.5-10.1.2.jar                    |AttributeFix                  |attributefix                  |10.1.2              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		dungeons_mobs-1.16.5-1.0.5.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.5               |DONE      |NOSIGNATURE
		SneakyMagic-v1.3.2-1.16.5.jar                     |Sneaky Magic                  |sneakymagic                   |1.3.2               |DONE      |9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Kobolds-1.2.2.jar                                 |Kobolds                       |kobolds                       |1.0.0               |DONE      |NOSIGNATURE
		Undefeatables+1.4.jar                             |Undefeatables                 |undefeatables                 |1.4                 |DONE      |NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.1.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.1               |DONE      |NOSIGNATURE
		SkyrimCraft+Perhaps+the+Final+Version.jar         |SkyrimCraft Official          |skyrimofficial                |1.6                 |DONE      |NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |DONE      |NOSIGNATURE
		EpicFightMod-1.16.5-3.2.2.jar                     |Epic Fight Mod                |epicfight                     |1.0                 |DONE      |NOSIGNATURE
		mgui-1.16.5-3.2.0.jar                             |mgui                          |mgui                          |3.2.0               |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		Artifacts-1.16.5-2.9.3.jar                        |Artifacts                     |artifacts                     |1.16.5-2.9.3        |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |NOSIGNATURE
		reliquary-1.16.5-1.3.5.1098.jar                   |Reliquary                     |xreliquary                    |1.16.5-1.3.5.1098   |DONE      |NOSIGNATURE
		ProgressiveBosses-2.2.0-mc1.16.x.jar              |Progressive Bosses            |progressivebosses             |2.2.0               |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		projectdawn-1.16.4-1.1.1.jar                      |Dawn to Dusk                  |projectdawn                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Lycanthropes-v1.5.5-1.16.5.jar                    |Lycanthropes                  |lycanthropes                  |1.0.0               |DONE      |NOSIGNATURE
		FpsReducer-mc1.16.4-1.18.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.4-1.18       |DONE      |NOSIGNATURE
		cameraoverhaul-1.0-1.16.4.jar                     |Camera Overhaul               |cameraoverhaul                |1.0.0               |DONE      |NOSIGNATURE
		runesword-1.16.5-1.3.0.jar                        |Runesword                     |runesword                     |1.16.5-1.3.0        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.17-universal.jar                |Forge                         |forge                         |36.1.17             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		LostTrinkets-1.16.5-0.1.27.jar                    |Lost Trinkets                 |losttrinkets                  |0.1.27              |DONE      |NOSIGNATURE
		simpletomb-1.16.5-1.0.6.jar                       |Simple Tombstone              |simpletomb                    |1.16.5-1.0.6        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Project+Brazier-1.16.5-0.5.2.2.jar                |Project Brazier               |projectbrazier                |0.5.2.1             |DONE      |NOSIGNATURE
		dungeonsarise1.16.4-1.2.61a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.61a             |DONE      |NOSIGNATURE
		UselessSword-1.16.5-V1.3.3.jar                    |Useless Sword                 |useless_sword                 |1.3.3               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.17-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		mana-and-artifice-1.3.0.6.jar                     |Mana and Artifice             |mana-and-artifice             |1.3.0.6             |DONE      |NOSIGNATURE
		greekfantasy-16.4.17.jar                          |Greek Fantasy                 |greekfantasy                  |16.4.17             |DONE      |NOSIGNATURE
		EntityCulling-1.16.5-2.1.2.jar                    |Entity Culling                |entity_culling                |2.1.2               |DONE      |NOSIGNATURE
		EndRemastered-R36.jar                             |End Remastered 3.6            |endrem                        |1.16.3              |DONE      |NOSIGNATURE
		Lollipop-1.16.5-3.2.9 (1).jar                     |Lollipop                      |lollipop                      |3.2.9               |DONE      |NOSIGNATURE
		rpgbackpacks-1.16.5-1.1.1.jar                     |RPG Backpacks                 |rpg_backpacks                 |1.1.1               |DONE      |NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |NOSIGNATURE
		storage_overhaul-1.16.5-1.0.4.jar                 |Storage Overhaul              |storage_overhaul              |1.16.5-1.0.4        |DONE      |NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		tetra-1.16.5-3.11.1.jar                           |Tetra                         |tetra                         |3.11.1              |DONE      |NOSIGNATURE
		relics-0.1.13.1.jar                               |Relics                        |relics                        |0.1.13.1            |DONE      |NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |DONE      |NOSIGNATURE
		overworld_two-1.0-Forge-1.16.4.jar                |Overworld 2                   |overworld_two                 |1.0                 |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimap                  |21.10.0.3           |DONE      |NOSIGNATURE
		FastWorkbench-1.16.4-4.5.1.jar                    |FastWorkbench                 |fastbench                     |4.5.1               |DONE      |NOSIGNATURE
		Hardcore+Battle+Towers+4.2.4.jar                  | Harcore Battle Towers 4.2.4  |hardcorebattletowers          |4.2.3               |DONE      |NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.2.2.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.2.2               |DONE      |NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.49.jar                   |Gobber 2                      |gobber2                       |2.3.48              |DONE      |NOSIGNATURE
		EnigmaticLegacy-2.11.4.jar                        |Enigmatic Legacy              |enigmaticlegacy               |2.11.4              |DONE      |NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |DONE      |NOSIGNATURE
		constructionwand-1.16.5-2.0.jar                   |Construction Wand             |constructionwand              |1.16.5-2.0          |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.7.12.jar                       |Vampirism                     |vampirism                     |1.7.12              |DONE      |NOSIGNATURE
		ferritecore-2.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.3               |DONE      |41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		occultism-1.16.5-1.2.3.jar                        |Occultism                     |occultism                     |1.16.5-1.2.3        |DONE      |NOSIGNATURE
		EasyPaxel(1.16.3)+-+1.0.10.jar                    |Easy Paxel                    |easypaxelmod                  |1.16.3-1.0.10       |DONE      |NOSIGNATURE
		mannequins-1.0.0-1.16.5-forge.jar                 |Mannequins                    |mannequins                    |1.0.0               |DONE      |NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |DONE      |NOSIGNATURE
		GameMenuModOption-1.16.4-1.5.jar                  |Game Menu Mod Option          |gamemenumodoption             |1.5                 |DONE      |NOSIGNATURE
		marg-1.16.5-0.6.jar                               |Dark Roleplay MARG            |marg                          |1                   |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.16.jar                  |GeckoLib                      |geckolib3                     |3.0.16              |DONE      |NOSIGNATURE
		dungeons_gear-1.16.5-3.0.16.jar                   |Dungeons Gear                 |dungeons_gear                 |3.0.16              |DONE      |NOSIGNATURE
	Crash Report UUID: 870d180f-8006-49f4-af2b-276ceb964c12
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['FazeAlpha'/6172, l='ServerLevel[The Elder Scrolls]', x=-46.36, y=76.77, z=496.59]]
	Data Packs: vanilla, mod:cyclopscore, mod:hermaeusmoramod, mod:wyrmroost (incompatible), mod:locks, mod:coldsteel (incompatible), mod:jei, mod:everlastingabilities, mod:attributefix, mod:dungeons_mobs (incompatible), mod:sneakymagic, mod:kobolds, mod:undefeatables, mod:guideapi-vp (incompatible), mod:skyrimofficial, mod:neat (incompatible), mod:forgeendertech, mod:epicfight, mod:mgui (incompatible), mod:placebo (incompatible), mod:artifacts, mod:dungeoncrawl, mod:xreliquary, mod:progressivebosses, mod:waila, mod:projectdawn, mod:lycanthropes, mod:fpsreducer, mod:cameraoverhaul, mod:runesword, mod:forge, mod:losttrinkets, mod:simpletomb (incompatible), mod:projectbrazier, mod:dungeons_arise, mod:useless_sword, mod:mana-and-artifice, mod:greekfantasy, mod:entity_culling, mod:endrem, mod:lollipop, mod:rpg_backpacks, mod:smoothboot, mod:storage_overhaul, mod:playerex, mod:curios, mod:tetra, mod:relics, mod:patchouli (incompatible), mod:overworld_two, mod:xaerominimap, mod:fastbench (incompatible), mod:hardcorebattletowers, mod:inventoryhud, mod:gobber2, mod:enigmaticlegacy, mod:fastfurnace (incompatible), mod:constructionwand (incompatible), mod:vampirism, mod:ferritecore (incompatible), mod:occultism, mod:easypaxelmod (incompatible), mod:mannequins, mod:expandability, mod:gamemenumodoption, mod:marg, mod:geckolib3 (incompatible), mod:dungeons_gear, generated/MARG
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'[](url)

**Comment by Kurojime** [comment]
How do I at least temporally fix till the bug fixes updates are up?

**Comment by Mithion** [comment]
This looks like a bug with epic fight mod, but it's possible an event is being raised by M&A on witch hunter arrows that shouldn't be. I'd raise the issue on their github as well and I'll double check on my end too.

**Comment by Mithion** [comment]
Confirming this is not an issue with M&A; I double checked the code and there's nothing in the entity registry or overrides that would classify the Witch Hunter Arrow as a living entity.
