### ISSUE TITLE
Crash after Ritual of Arcana

### ISSUE THREAD

**Issue by TefraK** [Mithion/Mana-And-Artifice#319]
I completed the Ritual of Arcana for a Projectile Fire Damage spell (with Damage, Speed and Range), and the game suddenly crashed.

I expected to get the spell like always, but I didn't. The ritual started, the "magic star" appeared, then the game freezed and crashed. I tried two times, in case it was a one-time thing, but it was the same.

 - Mod Version: [1.4.0.8]
 - Forge Version [36.2.2]

I'm using MultiMC to run the mods, these are:
AppleSkin 2.1.0
Curious 4.0.5.2
GeckoLib 3.0.43
JEI 7.7.1.116
ToroHealth 4
Xaeros Minimap 21.14.1
Mana And Artifice (obviously) 1.4.0.8

Btw every time I reopen the game, the ritual is still there, it just isn't active. If I activate it, the game crashes.

Edit:
Forgot the crash log

[00:23:35] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 473412a9-bb5b-4e3b-9cd8-73cd0a19dc74
[00:23:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271] {}
Caused by: java.lang.IllegalStateException: Tag mana-and-artifice:dynamic-modifier-3 used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.ma.tools.MATags.isItemEqual(MATags.java:31) ~[mana-and-artifice:1.4.0.8] {re:classloading}
	at com.ma.blocks.tileentities.TileEntityChalkRune.MatchesReagent(TileEntityChalkRune.java:118) ~[mana-and-artifice:1.4.0.8] {re:classloading}
	at com.ma.entities.rituals.EntityRitual.logic_stateGatheringReagents(EntityRitual.java:181) ~[mana-and-artifice:1.4.0.8] {re:classloading}
	at com.ma.entities.rituals.EntityRitual.runStateLogic(EntityRitual.java:138) ~[mana-and-artifice:1.4.0.8] {re:classloading}
	at com.ma.entities.rituals.EntityRitual.func_70071_h_(EntityRitual.java:360) ~[mana-and-artifice:1.4.0.8] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed
Il processo si è chiuso con codice 255.

**Comment by Mithion** [comment]
Duplicate (root cause) of #310
