### ISSUE TITLE
[1.18.2] Crash report

### ISSUE THREAD

**Issue by KennyA090** [Mithion/Mana-And-Artifice#590]
I entered the nether after my friend left his fire mote in the eldrin alter trying to make a greater mote for a while. When i reentered the overworld i crashed with this error:

---- Minecraft Crash Report ----
// Don't do that.

Time: 1/15/23, 9:17 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_36316_()" because "player" is null
	at com.mna.api.blocks.tile.IPowerConsumerTile.consume(IPowerConsumerTile.java:44) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at com.mna.blocks.tileentities.EldrinAltarTile.lambda$tickLogic_consumePower$8(EldrinAltarTile.java:763) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {}
	at com.mna.blocks.tileentities.EldrinAltarTile.tickLogic_consumePower(EldrinAltarTile.java:753) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at com.mna.blocks.tileentities.EldrinAltarTile.Tick(EldrinAltarTile.java:228) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at com.mna.blocks.artifice.EldrinAltarBlock.lambda$getTicker$0(EldrinAltarBlock.java:33) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mna.api.blocks.tile.IPowerConsumerTile.consume(IPowerConsumerTile.java:44) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at com.mna.blocks.tileentities.EldrinAltarTile.lambda$tickLogic_consumePower$8(EldrinAltarTile.java:763) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {}
	at com.mna.blocks.tileentities.EldrinAltarTile.tickLogic_consumePower(EldrinAltarTile.java:753) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at com.mna.blocks.tileentities.EldrinAltarTile.Tick(EldrinAltarTile.java:228) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at com.mna.blocks.artifice.EldrinAltarBlock.lambda$getTicker$0(EldrinAltarBlock.java:33) ~[mna-1.7.2.10.jar%2369!/:1.7.2.10] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Block entity being ticked --
Details:
	Name: mna:runic_altar_tile // com.mna.blocks.tileentities.EldrinAltarTile
	Block: Block{mna:eldrin_altar}[brimstone=false,connected=false,east=false,facing=north,north=false,show_sign=false,south=false,waterlogged=false,west=false]
	Block location: World: (-1356,87,1716), Section: (at 4,7,4 in -85,5,107; chunk contains blocks -1360,-64,1712 to -1345,319,1727), Region: (-3,3; contains chunks -96,96 to -65,127, blocks -1536,-64,1536 to -1025,319,2047)
	Block: Block{mna:eldrin_altar}[brimstone=false,connected=false,east=false,facing=north,north=false,show_sign=false,south=false,waterlogged=false,west=false]
	Block location: World: (-1356,87,1716), Section: (at 4,7,4 in -85,5,107; chunk contains blocks -1360,-64,1712 to -1345,319,1727), Region: (-3,3; contains chunks -96,96 to -65,127, blocks -1536,-64,1536 to -1025,319,2047)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['bbullet09'/71, l='ServerLevel[fUg]', x=-1322.72, y=86.00, z=1692.50]]
	Chunk stats: 4349
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,81,0), Section: (at 0,1,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 8240524 game time, 8409789 day time
	Level name: fUg
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 39428 (now: false), thunder time: 35870 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4728180320 bytes (4509 MiB) / 7113539584 bytes (6784 MiB) up to 21038628864 bytes (20064 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 56254.47
	Virtual memory used (MB): 22872.42
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 95.54
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx20064m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['bbullet09'/71, l='ServerLevel[fUg]', x=-1322.72, y=86.00, z=1692.50]]
	Data Packs: vanilla, mod:mna (incompatible), mod:mowziesmobs (incompatible), mod:mousetweaks (incompatible), mod:guardvillagers (incompatible), mod:balm (incompatible), mod:jei (incompatible), mod:potionbundles (incompatible), mod:nameless_trinkets (incompatible), mod:forge, mod:curios (incompatible), mod:twilightforest (incompatible), mod:patchouli (incompatible), mod:ars_nouveau, mod:waystones (incompatible), mod:geckolib3 (incompatible), mod:arsomega (incompatible), mod:journeymap, mod:dungeons_arise, mod:citadel (incompatible), mod:iceandfire (incompatible), mod:oreexcavation, mod:naturescompass (incompatible), mod:ars_elemental (incompatible), mod:rhino (incompatible), mod:easier_sleeping, mod:gravestone (incompatible), mod:architectury (incompatible), mod:inventorysorter (incompatible), mod:simplybackpacks (incompatible), mod:quickstoreremade
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		inventorysorter-1.18-19.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              |DONE      |Manifest: NOSIGNATURE
		rhino-forge-1802.2.1-build.255.jar                |Rhino                         |rhino                         |1802.2.1-build.255  |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.32.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.32              |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		EasierSleeping-1.18.2-2.1.0.jar                   |Easier Sleeping               |easier_sleeping               |2.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |DONE      |Manifest: NOSIGNATURE
		Nameless Trinkets-1.18.2-1.6.9.jar                |Nameless Trinkets             |nameless_trinkets             |1.18.2-1.6.9        |DONE      |Manifest: NOSIGNATURE
		simplybackpacks-1.18.2-2.1.2-build.40.jar         |Simply Backpacks              |simplybackpacks               |1.18.2-2.1.2-build.4|DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		arsomega-2.7.1.jar                                |Ars Omega                     |arsomega                      |1.18.2-2.7.1        |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.9.0-forge.jar                 |Journeymap                    |journeymap                    |5.9.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.10.162.jar                        |OreExcavation                 |oreexcavation                 |1.10.162            |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  |DONE      |Manifest: NOSIGNATURE
		mna-1.7.2.10.jar                                  |Mana and Artifice             |mna                           |1.7.2.10            |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		architectury-4.10.88-forge.jar                    |Architectury                  |architectury                  |4.10.88             |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.11-1.18.2-SNAPSHOT+build.2022-12-30|Ice and Fire                  |iceandfire                    |2.1.11-1.18.2-SNAPSH|DONE      |Manifest: NOSIGNATURE
		balm-3.2.1+0.jar                                  |Balm                          |balm                          |3.2.1+0             |DONE      |Manifest: NOSIGNATURE
		potionbundles-1.18.1-1.5.jar                      |Potion Bundles                |potionbundles                 |1.5                 |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.2-2.8.0.jar                      |Ars Nouveau                   |ars_nouveau                   |2.8.0               |DONE      |Manifest: NOSIGNATURE
		ars_elemental-1.18.2-0.4.9.8.jar                  |Ars Elemental                 |ars_elemental                 |1.18.2-0.4.9.8      |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.18.2-4.1.1423-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1423            |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.2-2.1.52-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.52-1.18.2       |DONE      |Manifest: NOSIGNATURE
		quickstoreremade-1.18.2-v1.0.0.jar                |Quick Store Remade            |quickstoreremade              |1.0                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 62cfdde1-20fa-4a7b-ad3e-592f03087115
	FML: 40.2
	Forge: net.minecraftforge:40.2.0

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
