### ISSUE TITLE
[1.19.2] unable to join server

### ISSUE THREAD

**Issue by LKD-PIX** [Mithion/Mana-And-Artifice#638]
**Describe the bug**
Upon connecting to a dedicated server it errors because it can't cast some function

**To Reproduce**
1. install on a forge server and client
2. join

**Screenshots**

<details>
  <summary>error code</summary>
<pre>
java.lang.ClassCastException: class com.mna.loot.RandomJournalPage cannot be cast to class net.minecraft.world.level.storage.loot.functions.SetContainerContents (com.mna.loot.RandomJournalPage is in module mna@2.1.0.1 of loader 'TRANSFORMER' @3a04e083; net.minecraft.world.level.storage.loot.functions.SetContainerContents is in module minecraft@1.19.2 of loader 'TRANSFORMER' @3a04e083)
	at net.minecraft.world.level.storage.loot.functions.SetContainerContents$Serializer.m_6170_(SetContainerContents.java:101) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:125) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2370!/:?] {}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:210) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:187) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2370!/:?] {}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:279) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:253) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2370!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:55) ~[rer-2.6.1_PIX.jar%23897!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.players.PlayerList.handler$dmj000$onPlayerConnect(PlayerList.java:2452) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:247) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:APP:mixins.longerlogintimes.json:ServerLoginPacketListenerImplMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:APP:mixins.longerlogintimes.json:ServerLoginPacketListenerImplMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:APP:mixins.longerlogintimes.json:ServerLoginPacketListenerImplMixin,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%231009!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1623) [?:?] {re:mixin}
</pre>

</details>

**Version Information (please complete the following information):**
 - Mod Version: 2.1.0.1
 - Forge Version: 43.3.2

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.

**Comment by LKD-PIX** [comment]
Hey, understandable, but as i am developing a large modpack for 1.19, may you consider releasing the source code only for this 1.19.2 build?
Or may you allow me to redistribute a modified version where i edit the IL code?
Im just somehow looking to fix the bugs and some compatibility with other mods as i would love to have your mod in the pack .-.
