### ISSUE TITLE
[1.20.1] java.lang.ClassCastException with Skeleton Assassin Shuriken

### ISSUE THREAD

**Issue by aszecsei** [Mithion/Mana-And-Artifice#659]
**Describe the bug**
Loaded up the 1.20.1 alpha on my custom modpack. Immediately getting Neruina reports of ticking entity exceptions:

```java.lang.ClassCastException: class com.mna.entities.projectile.SkeletonAssassinShuriken cannot be cast to class net.minecraft.world.entity.LivingEntity (com.mna.entities.projectile.SkeletonAssassinShuriken is in module mna@3.0.0.1 of loader 'TRANSFORMER' @2e564c78; net.minecraft.world.entity.LivingEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @2e564c78)```

**To Reproduce**
Not sure how reproducible this is, given it occurred in a sizeable modpack and did not appear to do so when I installed the mod into a more minimal environment (though I also may not have encountered the SkeletonAssassinShuriken projectiles in that minimal environment?)

It might have also occurred due to an interaction with Apothic Attributes since it first appeared immediately after a mixin from that mod?

**Expected behavior**
N/A

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0] 3.0.0.1
 - Forge Version [e.g. 36.1.32] NeoForge 47.1.84

**Additional context**
Exception trace: https://mclo.gs/r8C9C3y
Full log: https://mclo.gs/qwHyyyb

**Comment by lanwoodall423** [comment]
Same issue but I don't have Apothic Attributes

**Comment by lanwoodall423** [comment]
From latest log

`net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class com.mna.entities.projectile.SkeletonAssassinShuriken cannot be cast to class net.minecraft.world.entity.LivingEntity (com.mna.entities.projectile.SkeletonAssassinShuriken is in module mna@3.0.0.1 of loader 'TRANSFORMER' @5d8a1456; net.minecraft.world.entity.LivingEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @5d8a1456)
	at net.minecraft.world.entity.LivingEntity.handler$fef000$checkValkValorEffect(LivingEntity.java:18547) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6515_(LivingEntity.java) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6475_(LivingEntity.java:1618) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1110) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at com.mna.entities.faction.base.BaseFactionMob.m_6469_(BaseFactionMob.java:221) ~[mna-forge-1.20.1-3.0.0.1-all.jar%23728!/:3.0.0.1]
	at com.mna.entities.faction.Barkling.m_6469_(Barkling.java:198) ~[mna-forge-1.20.1-3.0.0.1-all.jar%23728!/:3.0.0.1]
	at com.mna.entities.projectile.SkeletonAssassinShuriken.m_5790_(SkeletonAssassinShuriken.java:76) ~[mna-forge-1.20.1-3.0.0.1-all.jar%23728!/:3.0.0.1]
	at net.minecraft.world.entity.projectile.Projectile.m_6532_(Projectile.java:138) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.m_8119_(AbstractArrow.java:192) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.level.ServerLevel.track(ServerLevel.java:7169) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$dkn000$onTickNonPassenger(ServerLevel.java:7185) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23743!/:2.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:25) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23743!/:2.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:3041) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?]
	... 5 more`
[crash-2023-12-29_18.43.39-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/13796535/crash-2023-12-29_18.43.39-server.txt)

**Comment by lanwoodall423** [comment]
First two lines of my crash were:

```
java.lang.ClassCastException: class com.mna.entities.projectile.SkeletonAssassinShuriken cannot be cast to class net.minecraft.world.entity.LivingEntity (com.mna.entities.projectile.SkeletonAssassinShuriken is in module mna@3.0.0.1 of loader 'TRANSFORMER' @5d8a1456; net.minecraft.world.entity.LivingEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @5d8a1456)
	at net.minecraft.world.entity.LivingEntity.handler$fef000$**checkValkValorEffect**(LivingEntity.java:18547) ~[client-1.20.1-20230612.114412-srg.jar%23876!/:?] 
```
	
Deep Aether updated today noting "Fixed critical Valkyrie's Valor bug that crashes the game"

I'm no longer able to reproduce this issue.
