### ISSUE TITLE
Crash on use of Smite with Light 

### ISSUE THREAD

**Issue by BigManAl** [Mithion/Mana-And-Artifice#85]
Activating Smite with Light spell causes game to crash.
Mana and Artifice version: 1.1.0.1
Forge version: 34.1.42

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/16/20 5:21 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.ma.network.messages.to_client.RoteProgressSyncMessageToClient.<init>(RoteProgressSyncMessageToClient.java:26) ~[?:1.1.0.1] {re:classloading}
	at com.ma.network.messages.to_client.RoteProgressSyncMessageToClient.fromCapability(RoteProgressSyncMessageToClient.java:64) ~[?:1.1.0.1] {re:classloading}
	at com.ma.network.ServerMessageDispatcher.lambda$sendRoteSyncMessage$6(ServerMessageDispatcher.java:70) ~[?:1.1.0.1] {re:classloading}
	at com.ma.network.ServerMessageDispatcher$$Lambda$9181/86278139.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at com.ma.network.ServerMessageDispatcher.sendRoteSyncMessage(ServerMessageDispatcher.java:67) ~[?:1.1.0.1] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers.lambda$tickMagic$4(MACapabilityForgeEventHandlers.java:179) ~[?:1.1.0.1] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers$$Lambda$9180/1507360894.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers.tickMagic(MACapabilityForgeEventHandlers.java:177) ~[?:1.1.0.1] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers.onPlayerTick(MACapabilityForgeEventHandlers.java:134) ~[?:1.1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_173_MACapabilityForgeEventHandlers_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:90) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:266) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$8009/1525058830.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.ma.network.messages.to_client.RoteProgressSyncMessageToClient.<init>(RoteProgressSyncMessageToClient.java:26) ~[?:1.1.0.1] {re:classloading}
	at com.ma.network.messages.to_client.RoteProgressSyncMessageToClient.fromCapability(RoteProgressSyncMessageToClient.java:64) ~[?:1.1.0.1] {re:classloading}
	at com.ma.network.ServerMessageDispatcher.lambda$sendRoteSyncMessage$6(ServerMessageDispatcher.java:70) ~[?:1.1.0.1] {re:classloading}
	at com.ma.network.ServerMessageDispatcher$$Lambda$9181/86278139.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at com.ma.network.ServerMessageDispatcher.sendRoteSyncMessage(ServerMessageDispatcher.java:67) ~[?:1.1.0.1] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers.lambda$tickMagic$4(MACapabilityForgeEventHandlers.java:179) ~[?:1.1.0.1] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers$$Lambda$9180/1507360894.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers.tickMagic(MACapabilityForgeEventHandlers.java:177) ~[?:1.1.0.1] {re:classloading}
	at com.ma.capabilities.MACapabilityForgeEventHandlers.onPlayerTick(MACapabilityForgeEventHandlers.java:134) ~[?:1.1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_173_MACapabilityForgeEventHandlers_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:90) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:266) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 1
	Entity Name: SpaceBoi1
	Entity's Exact location: -194.92, 4.00, 345.60
	Entity's Block location: World: (-195,4,345), Chunk: (at 13,0,9 in -13,21; contains blocks -208,0,336 to -193,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$8009/1525058830.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by Mithion** [comment]
Not near a computer but I have a theory the same thing would happen with rift.  Could you perhaps test that one as well?

**Comment by BigManAl** [comment]
Rift works with smite.

**Comment by BigManAl** [comment]
It seems some spells crash on first activation but after a simple relog they work fine. Here's a couple examples.
[crash-2020-11-16_09.30.18-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/5543348/crash-2020-11-16_09.30.18-server.txt)
[crash-2020-11-16_09.33.21-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/5543349/crash-2020-11-16_09.33.21-server.txt)

**Comment by Mithion** [comment]
I believe I have this fixed in 1.1.0.2
