### ISSUE TITLE
Crash during map generation

### ISSUE THREAD

**Issue by wuzzard** [Mithion/Mana-And-Artifice#924]
**Describe the bug**
For new instances including MnA, when the world is generating, my game sometimes crashes. This appears to be a race condition and it doesn't always happen. My guess is that some specific item from MnA is generating in that particular seed which triggers the problem, but I'm speculating of course.

**To Reproduce**
I just need to generate a few maps for it to trigger. I thought it was related to my world generation mods, but I've gone through three different ones, and that doesn't _seem_ to be the direct cause.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.24
 - Forge Version: 47.3.5

**Additional context**
The relevant crash log entry is:

`java.lang.NullPointerException: Cannot invoke "java.lang.Double.floatValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.mna.config.SpellConfig.getConfiguredValue(SpellConfig.java:111) ~[mna-forge-1.20.1-3.0.0.24-all.jar%23448!/:3.0.0.24] {re:classloading}
...
`

From the startup log:

`[22:58:32] [Server thread/INFO]: M&A >> Baking Spell Config
[22:58:32] [Thread-3/INFO]: M&A >> Baking Spell Config
[22:58:32] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "java.lang.Double.floatValue()" because the return value of "java.util.HashMap.get(Object)" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.mna.config.SpellConfig onModConfigEvent(Lnet/minecraftforge/fml/event/config/ModConfigEvent;)V
		2: ASM: class com.mna.config.GeneralConfig onModConfigEvent(Lnet/minecraftforge/fml/event/config/ModConfigEvent;)V
		3: ASM: class com.mna.config.ClientConfig onModConfigEvent(Lnet/minecraftforge/fml/event/config/ModConfigEvent;)V
java.lang.NullPointerException: Cannot invoke "java.lang.Double.floatValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at TRANSFORMER/mna@3.0.0.24/com.mna.config.SpellConfig.getConfiguredValue(SpellConfig.java:111)
	at TRANSFORMER/mna@3.0.0.24/com.mna.apibridge.ConfigHelper.getConfiguredValue(ConfigHelper.java:31)
	at TRANSFORMER/mna@3.0.0.24/com.mna.api.spells.attributes.AttributeValuePair.lookupConfig(AttributeValuePair.java:42)
	at TRANSFORMER/mna@3.0.0.24/com.mna.api.spells.parts.Shape.lambda$lookupAttributeConfig$0(Shape.java:61)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/mna@3.0.0.24/com.mna.api.spells.parts.Shape.lookupAttributeConfig(Shape.java:61)
	at TRANSFORMER/mna@3.0.0.24/com.mna.api.spells.parts.Shape.getModifiableAttributes(Shape.java:56)
	at TRANSFORMER/mna@3.0.0.24/com.mna.config.SpellConfig.lambda$bakeConfig$1(SpellConfig.java:70)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/mna@3.0.0.24/com.mna.config.SpellConfig.bakeConfig(SpellConfig.java:69)
	at TRANSFORMER/mna@3.0.0.24/com.mna.config.SpellConfig.onModConfigEvent(SpellConfig.java:55)
	at TRANSFORMER/mna@3.0.0.24/com.mna.config.__SpellConfig_onModConfigEvent_ModConfigEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.3.5/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:44)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.5/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$8(ModContainer.java:170)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.5/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:170)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.5/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.5/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.5/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.5/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
	at TRANSFORMER/forge@47.3.5/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)`

Let me know if you want full logs and I'll attach them.

Thanks

**Comment by Mithion** [comment]
Please try without any M&A addons, I'm not able to replicate this in dev.  It's generating new configs just fine.

**Comment by wuzzard** [comment]
I created a new instance having only MnA and it's dependencies. I used  the following settings:

Name: mna-test-1
Difficulty: Hard
Allow Cheats: On
World Type: Large Biomes
Seed: mna-test-1
Bonus Chest: On

(everything else I left defaulted)

When I create a new world, the world startup locks just prior to getting the map creation progress indicators (so I guess the error technically happens just prior to map generation.)

Note 1: If I restart the instance and load the same game, it works. I'm guessing something is trying to access a config value before it is initialized the first time around.

Note 2: This appears to be a race condition, because it doesn't happen on every new map/game.


Attaching the logs and crash report.

[crash-2024-09-08_11.34.20-server.txt](https://github.com/user-attachments/files/16922757/crash-2024-09-08_11.34.20-server.txt)

[latest.log](https://github.com/user-attachments/files/16922758/latest.log)

**Comment by Mithion** [comment]
I just created 10 worlds in a row without issue - I did make a minor change to the configs so perhaps that was the fix.  We'll see if it is good for you as well with the next version.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.1

**Comment by fbfnysnshnsgnwg** [comment]
@Mithion i still get this issue in 3.1.0.4, even though you said it was fixed

[crash-2025-02-07_23.00.33-server.txt](https://github.com/user-attachments/files/18719274/crash-2025-02-07_23.00.33-server.txt)
modlist in crashlog

**Comment by Schwarin** [comment]
> [@Mithion](https://github.com/Mithion) i still get this issue in 3.1.0.4, even though you said it was fixed
> 
> [crash-2025-02-07_23.00.33-server.txt](https://github.com/user-attachments/files/18719274/crash-2025-02-07_23.00.33-server.txt) modlist in crashlog

same problem, but in 3.1.0.5!

[crash-2025-03-17_16.20.30-server.txt](https://github.com/user-attachments/files/19295745/crash-2025-03-17_16.20.30-server.txt)
