### ISSUE TITLE
Guidebook progress log spam

### ISSUE THREAD

**Issue by WindFox** [Mithion/Mana-And-Artifice#997]
**Describe the bug**
When the codex is opened, the log gets spammed with the following:
```
[Render thread/ERROR] [net.minecraftforge.fml.util.ObfuscationReflectionHelper/REFLECTION]: Unable to locate field progress (progress) on type net.minecraft.client.multiplayer.ClientAdvancements
net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: progress
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:227) ~[fmlcore-1.20.1-47.3.0.jar%23725!/:?]
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:72) ~[fmlcore-1.20.1-47.3.0.jar%23725!/:?]
	at com.mna.guide.GuideBookEntries.playerHasAdvancement(GuideBookEntries.java:81) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23636!/:3.1.0.1]
	at com.mna.guide.GuideBookEntries.getEntries(GuideBookEntries.java:92) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23636!/:3.1.0.1]
	at com.mna.gui.item.GuiGuideBook.setupCategoryItemButtons(GuiGuideBook.java:802) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23636!/:3.1.0.1]
	at com.mna.gui.item.GuiGuideBook.setupIndexView(GuiGuideBook.java:725) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23636!/:3.1.0.1]
	at com.mna.gui.item.GuiGuideBook.displayBreadcrumb(GuiGuideBook.java:680) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23636!/:3.1.0.1]
	at com.mna.gui.item.GuiGuideBook.m_6375_(GuiGuideBook.java:340) ~[mna-forge-1.20.1-3.1.0.1-all.jar%23636!/:3.1.0.1]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2386!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2398!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2386!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23724!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]
Caused by: java.lang.NoSuchFieldException: progress
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:221) ~[fmlcore-1.20.1-47.3.0.jar%23725!/:?]
	... 45 more
[Render thread/WARN] [com.mna.ManaAndArtifice/]: GuideBookEntries >> Error checking advancement completion on client!
```

**To Reproduce**
1. Get item Codex
2. Open Codex to view contents
3. See error in log
4. Keep playing

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version: 47.3
 or
 - NeoForge Version: 47.1.106

**Additional context**
Codex works fine. It's just the log gets spammed with this.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
